# link YouTrack task in a pull request's description
name: Link PR YT Task

on:
  pull_request_target:
    types: [opened]

jobs:
  linkYTTask:
    runs-on: ubuntu-latest
    steps:
      - name: Link PR YT Task
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            // get YouTrack task id (like CA-1337)
            const prBranchName = context.payload.pull_request.head.ref
            const match = prBranchName.match(/[A-Z]+-\d+/)

            if (!match) {
              return
            }

            const taskId = match[0]
            const taskLink = `[YouTrack Task](https://t.cryptorank.io/issue/${taskId})`
            const prBody = context.payload.pull_request.body

            // modify pr description
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: prBody ? `${taskLink}\n${prBody}` : taskLink
            })
            
            // add comment on pr
            await github.rest.issues.createComment({	
              owner: context.repo.owner,	
              repo: context.repo.repo,	
              issue_number: context.issue.number,	
              body: taskLink	
            })
